### PR TITLE
bug(back-button):gives pointer cursor to back button

### LINKED ISSUE #58: Make back button on a main page a pointer
**Is your feature request related to a problem? Please describe.**
Make back button on a main page a pointer

### PR DESCRIPTION
**Pull request by JorgeLVilla**
## Changes
1. Gives pointer cursor to Go Back button.

_If this closes an issue, name it here. If it doesn't, remove this line_
Closes #58

### CODE REVIEW

**Review by Gjhnsn — APPROVED** [review]
🤯

**Review by connielion — APPROVED** [review]
noice

**Review by BlackCubes — APPROVED** [review]
Nice pointer!

**Review by Lap343 — APPROVED** [review]
looking good!

**Pull request merged**
