### PR TITLE
feat(news-articles):add more details in the news articles and in their expanded view

### LINKED ISSUE #37: Fill the articles with more details
**Is your feature request related to a problem? Please describe.**
The articles need more details 

**Describe the solution you'd like**
For the articles to have more details of the fetched news articles

### PR DESCRIPTION
**Pull request by Lap343**
## Changes
1. add more details in the news articles and in their expanded view

## Purpose
To give the user more details

Closes #37

### CODE REVIEW

**Review by connielion — APPROVED** [review]
Very noice!

**Review by krferrell — APPROVED** [review]
Looks good. I do not see any issues.

**Review by BlackCubes — APPROVED** [review]
Looks clean!

**Review by gonzalespaulb — APPROVED** [review]
Cant wait to see the final product

**Review by JorgeLVilla — APPROVED** [review]
Nice job Luis!

**Pull request merged**
