### PR TITLE
Lp 78 one half article fix

### LINKED ISSUE #78: Fix two per row article info boxes
**Is your feature request related to a problem? Please describe.**
When you hover over one of the two per row articles the info box and the image separate from one another

**Describe the solution you'd like**
When the user hovers over the article it has the same styling as the other article on hover styles

### LINKED ISSUE #80: Load only 18 articles in main
**Is your feature request related to a problem? Please describe.**
20 articles is to many

**Describe the solution you'd like**
Only load 18 articles inside of the main page

### PR DESCRIPTION
**Pull request by Lap343**
## Changes
1. Made the image hover to stay in the same spot
2. Changed the number of articles loaded into the main page

## Purpose
So the image doesn't move on hover and so the article placement will look better

Closes #78 
Closes #80

### CODE REVIEW

**Review by BlackCubes — APPROVED** [review]
Kewl!

**Review by connielion — APPROVED** [review]
Noice

**Review by krferrell — APPROVED** [review]
Looks good

**Review by dannysanchez559 — APPROVED** [review]
quick and easyyy

**Pull request merged**
