### PR TITLE
feat(dependencies): add styled-components in the dependencies

### LINKED ISSUE #6: Install Styled Components
**Is your feature request related to a problem? Please describe.**
The app does not have Styled Components installed

**Describe the solution you'd like**
To install Styled Components

### PR DESCRIPTION
**Pull request by Lap343**
## Changes
1. Added styled components to our list of dependencies

## Purpose
So we can use styled components in our app

Closes #6

### CODE REVIEW

**Review by JorgeLVilla — APPROVED** [review]
Noiiceee job.

**Review by krferrell — APPROVED** [review]
Nice. I was looking at their release notes and 5.3.1 just came out today.

**Review by JayDampitan — APPROVED** [review]
Lets get it Luis!

**Comment by Lap343** [comment]
> Nice. I was looking at their release notes and 5.3.1 just came out today.

you right hopefully nothing is wrong with this release

**Pull request merged**
