### PR TITLE
bug(article):close button shows pointer on hover

### LINKED ISSUE #62: hover cursor on article close button
**Is your feature request related to a problem? Please describe.**
Cursor should show to user that the close button is a button when the user hovers over it.

### PR DESCRIPTION
**Pull request by JorgeLVilla**
## Changes
1. Gives the close button a pointer on hover.

_If this closes an issue, name it here. If it doesn't, remove this line_
Closes #62

### CODE REVIEW

**Review by Lap343 — APPROVED** [review]
A M A Z I N G ! ! !

**Review by Gjhnsn — APPROVED** [review]
Fantastic

**Review by BlackCubes — APPROVED** [review]
Nice and easy!

**Review by gonzalespaulb — APPROVED** [review]
Extensive

**Pull request merged**
