### PR TITLE
Jv 39 home button

### LINKED ISSUE #39: Home button for app
**Is your feature request related to a problem? Please describe.**
The app needs a home button to take you back to top news page.

**Describe the solution you'd like**
Add a button that renders the top news and today news back to main screen.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by JorgeLVilla**
## Changes
_List Changes Introduced by this PR_
1. Adds an on click function to make the logo clickable.

## Purpose
Allows the user to go home to show top news when clicking on the logo.

_If this closes an issue, name it here. If it doesn't, remove this line_
Closes #39

### CODE REVIEW

**Review by connielion — APPROVED** [review]
Looks good!

**Review by krferrell — APPROVED** [review]
Noicee

**Review by JayDampitan — APPROVED** [review]
Looking good Jorge!

**Review by Lap343 — APPROVED** [review]
I'm not set as a reviewer but I still say it's ok even if Jorge doesn't like me

**Comment by JorgeLVilla** [comment]
Hey Luis, you helped just a little little bit haha. You're my ex-Team captain for life!

**Pull request merged**
